#!/bin/sh

# Hotplug script for HP1020



[ "$ACTION" != "add" ] && exit 0

[ "$PRODUCT" != "03f0/2b17" ] && exit 0  # HP1020 VID/PID



echo "HP1020 plugged in, loading firmware..."

cat /usr/share/hp1020/sihp1020.dl > /dev/usb/lp0

sleep 2



# 启动 p910nd

if ! pidof p910nd >/dev/null; then

    /usr/sbin/p910nd -b -o /dev/usb/lp0 0

fi
